# Generated by Django 3.1.1 on 2021-03-12 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0002_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='confirm',
            new_name='rpassword',
        ),
    ]
