# Generated by Django 3.1.1 on 2021-03-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0003_auto_20210312_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(max_length=20, null=True, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=20, null=True, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='account',
            name='rpassword',
            field=models.CharField(max_length=20, null=True, verbose_name='confirm'),
        ),
    ]
