# Generated by Django 3.1.1 on 2021-03-13 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0005_auto_20210312_1415'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='User',
        ),
    ]
